import { Province } from '../../src/generated/prisma/enums.js';
import type { DistrictCreateInput } from '../../src/generated/prisma/models.js';

/** Sri Lanka's 25 districts. Kept identical to the web app's src/data/districts.ts. */
export const DISTRICTS: DistrictCreateInput[] = [
  {
    id: 'colombo',
    name: 'Colombo',
    nameSi: 'කොළඹ',
    nameTa: 'கொழும்பு',
    province: Province.WESTERN,
    tagline: 'The city that never slows down',
    description:
      'Commercial heart of Sri Lanka — sea breeze at Galle Face, the buzz of Pettah, and a skyline that keeps growing.',
    famousFor: ['Galle Face Green', 'Pettah Market', 'Gangaramaya Temple', 'Street food'],
    colorFrom: '#0f4c81',
    colorTo: '#1b998b',
  },
  {
    id: 'gampaha',
    name: 'Gampaha',
    nameSi: 'ගම්පහ',
    nameTa: 'கம்பகா',
    province: Province.WESTERN,
    tagline: 'Lagoons, temples and the gateway to the island',
    description: 'Home to the airport, Negombo’s fishing culture and the sacred Kelaniya Raja Maha Vihara.',
    famousFor: ['Negombo Lagoon', 'Kelaniya Temple', 'Henarathgoda Gardens'],
    colorFrom: '#1b6f5c',
    colorTo: '#6bbf59',
  },
  {
    id: 'kalutara',
    name: 'Kalutara',
    nameSi: 'කළුතර',
    nameTa: 'களுத்துறை',
    province: Province.WESTERN,
    tagline: 'Rivers, rubber and golden beaches',
    description:
      'Where the Kalu Ganga meets the sea — famous for its hollow stupa, mangosteen season and quiet coastline.',
    famousFor: ['Kalutara Bodhiya', 'Brief Garden', 'Mangosteen', 'Beaches'],
    colorFrom: '#155e75',
    colorTo: '#f59e0b',
  },
  {
    id: 'kandy',
    name: 'Kandy',
    nameSi: 'මහනුවර',
    nameTa: 'கண்டி',
    province: Province.CENTRAL,
    tagline: 'The hill capital with a royal heart',
    description:
      'Last royal kingdom of Sri Lanka, home of the Temple of the Sacred Tooth Relic and the Esala Perahera.',
    famousFor: ['Temple of the Tooth', 'Kandy Lake', 'Esala Perahera', 'Peradeniya Gardens'],
    colorFrom: '#8d153a',
    colorTo: '#eb7400',
  },
  {
    id: 'matale',
    name: 'Matale',
    nameSi: 'මාතලේ',
    nameTa: 'மாத்தளை',
    province: Province.CENTRAL,
    tagline: 'Spices, rock fortresses and cave temples',
    description:
      'Spice gardens, the Sigiriya rock fortress and the Dambulla cave temples — history everywhere you look.',
    famousFor: ['Sigiriya', 'Dambulla Cave Temple', 'Spice gardens', 'Aluvihare'],
    colorFrom: '#7c2d12',
    colorTo: '#d97706',
  },
  {
    id: 'nuwara-eliya',
    name: 'Nuwara Eliya',
    nameSi: 'නුවරඑළිය',
    nameTa: 'நுவரெலியா',
    province: Province.CENTRAL,
    tagline: 'Little England in the clouds',
    description: 'Cool mist, endless tea estates and the highest plains on the island. Bring a jacket.',
    famousFor: ['Tea estates', 'Horton Plains', 'Gregory Lake', 'Strawberries'],
    colorFrom: '#14532d',
    colorTo: '#4ade80',
  },
  {
    id: 'galle',
    name: 'Galle',
    nameSi: 'ගාල්ල',
    nameTa: 'காலி',
    province: Province.SOUTHERN,
    tagline: 'Fort walls and ocean sunsets',
    description: 'A living UNESCO fort, stilt fishermen at Koggala and some of the best beaches in the south.',
    famousFor: ['Galle Fort', 'Unawatuna', 'Stilt fishermen', 'Surfing'],
    colorFrom: '#0e7490',
    colorTo: '#fbbf24',
  },
  {
    id: 'matara',
    name: 'Matara',
    nameSi: 'මාතර',
    nameTa: 'மாத்தறை',
    province: Province.SOUTHERN,
    tagline: 'The southern tip of the island',
    description: 'Whales off Mirissa, the Dondra lighthouse and a coastline made for slow days.',
    famousFor: ['Mirissa', 'Dondra Lighthouse', 'Polhena Beach', 'Whale watching'],
    colorFrom: '#1e40af',
    colorTo: '#38bdf8',
  },
  {
    id: 'hambantota',
    name: 'Hambantota',
    nameSi: 'හම්බන්තොට',
    nameTa: 'அம்பாந்தோட்டை',
    province: Province.SOUTHERN,
    tagline: 'Leopards, lagoons and buffalo curd',
    description:
      'Dry-zone wilderness with Yala and Bundala, salt pans, and the best curd and treacle you will ever have.',
    famousFor: ['Yala National Park', 'Bundala', 'Tangalle beaches', 'Curd & treacle'],
    colorFrom: '#92400e',
    colorTo: '#facc15',
  },
  {
    id: 'jaffna',
    name: 'Jaffna',
    nameSi: 'යාපනය',
    nameTa: 'யாழ்ப்பாணம்',
    province: Province.NORTHERN,
    tagline: 'Culture, kovils and the best crab curry',
    description: 'Proud Tamil heritage, the golden Nallur Kovil, palmyrah everything and legendary Jaffna mangoes.',
    famousFor: ['Nallur Kovil', 'Jaffna Fort', 'Casuarina Beach', 'Crab curry'],
    colorFrom: '#b45309',
    colorTo: '#dc2626',
  },
  {
    id: 'kilinochchi',
    name: 'Kilinochchi',
    nameSi: 'කිලිනොච්චිය',
    nameTa: 'கிளிநொச்சி',
    province: Province.NORTHERN,
    tagline: 'Rebuilding with resilience',
    description: 'Farmland fed by the great Iranamadu tank — a district of hard work and new beginnings.',
    famousFor: ['Iranamadu Tank', 'Elephant Pass', 'Paddy fields', 'Palmyrah'],
    colorFrom: '#3f6212',
    colorTo: '#a3e635',
  },
  {
    id: 'mannar',
    name: 'Mannar',
    nameSi: 'මන්නාරම',
    nameTa: 'மன்னார்',
    province: Province.NORTHERN,
    tagline: 'Baobabs, birds and Adam’s Bridge',
    description: 'An island of its own — ancient baobab trees, migratory flamingos and the chain of shoals to India.',
    famousFor: ['Baobab tree', 'Mannar Fort', 'Madhu Church', 'Flamingos'],
    colorFrom: '#0f766e',
    colorTo: '#f472b6',
  },
  {
    id: 'vavuniya',
    name: 'Vavuniya',
    nameSi: 'වව්නියාව',
    nameTa: 'வவுனியா',
    province: Province.NORTHERN,
    tagline: 'The gateway to the North',
    description: 'A crossroads town where the A9 carries everyone north — calm tanks, markets and warm people.',
    famousFor: ['A9 highway', 'Madukanda Vihara', 'Kandasamy Kovil', 'Local markets'],
    colorFrom: '#6d28d9',
    colorTo: '#f59e0b',
  },
  {
    id: 'mullaitivu',
    name: 'Mullaitivu',
    nameSi: 'මුලතිව්',
    nameTa: 'முல்லைத்தீவு',
    province: Province.NORTHERN,
    tagline: 'Untouched lagoons on the north-east coast',
    description: 'Quiet beaches, Nayaru and Kokkilai lagoons, and a coastline still waiting to be discovered.',
    famousFor: ['Nayaru Lagoon', 'Kokkilai Lagoon', 'Quiet beaches', 'Fresh seafood'],
    colorFrom: '#075985',
    colorTo: '#34d399',
  },
  {
    id: 'batticaloa',
    name: 'Batticaloa',
    nameSi: 'මඩකලපුව',
    nameTa: 'மட்டக்களப்பு',
    province: Province.EASTERN,
    tagline: 'Land of the singing fish',
    description: 'A lagoon town with a Dutch fort, Kallady bridge and the calm shallow waters of Pasikudah.',
    famousFor: ['Singing fish', 'Pasikudah', 'Kallady Bridge', 'Batticaloa Lagoon'],
    colorFrom: '#0369a1',
    colorTo: '#a78bfa',
  },
  {
    id: 'ampara',
    name: 'Ampara',
    nameSi: 'අම්පාර',
    nameTa: 'அம்பாறை',
    province: Province.EASTERN,
    tagline: 'World-class waves and wild parks',
    description: 'Arugam Bay draws surfers from around the world, while Kumana and Gal Oya stay wonderfully wild.',
    famousFor: ['Arugam Bay', 'Kumana National Park', 'Gal Oya', 'Paddy fields'],
    colorFrom: '#0284c7',
    colorTo: '#fde047',
  },
  {
    id: 'trincomalee',
    name: 'Trincomalee',
    nameSi: 'ත්‍රිකුණාමලය',
    nameTa: 'திருகோணமலை',
    province: Province.EASTERN,
    tagline: 'A natural harbour and turquoise seas',
    description: 'Koneswaram temple on the cliffs, Nilaveli sands and snorkelling at Pigeon Island.',
    famousFor: ['Koneswaram Temple', 'Nilaveli', 'Pigeon Island', 'Whale watching'],
    colorFrom: '#0891b2',
    colorTo: '#2dd4bf',
  },
  {
    id: 'kurunegala',
    name: 'Kurunegala',
    nameSi: 'කුරුණෑගල',
    nameTa: 'குருணாகல்',
    province: Province.NORTH_WESTERN,
    tagline: 'Rocks, kings and the coconut triangle',
    description: 'Ringed by giant rock outcrops, once a royal capital and now the heart of coconut country.',
    famousFor: ['Ethagala rock', 'Ridi Viharaya', 'Coconut triangle', 'Yapahuwa'],
    colorFrom: '#57534e',
    colorTo: '#84cc16',
  },
  {
    id: 'puttalam',
    name: 'Puttalam',
    nameSi: 'පුත්තලම',
    nameTa: 'புத்தளம்',
    province: Province.NORTH_WESTERN,
    tagline: 'Dolphins, kitesurfing and salt pans',
    description: 'Kalpitiya’s dolphins and kite winds, shimmering salt pans and the edge of Wilpattu.',
    famousFor: ['Kalpitiya', 'Dolphin watching', 'Salt pans', 'Kitesurfing'],
    colorFrom: '#1d4ed8',
    colorTo: '#e2e8f0',
  },
  {
    id: 'anuradhapura',
    name: 'Anuradhapura',
    nameSi: 'අනුරාධපුරය',
    nameTa: 'அனுராதபுரம்',
    province: Province.NORTH_CENTRAL,
    tagline: 'The first great kingdom',
    description: 'Sacred city of the Sri Maha Bodhi and giant dagobas — over two thousand years of history.',
    famousFor: ['Sri Maha Bodhi', 'Ruwanwelisaya', 'Mihintale', 'Ancient tanks'],
    colorFrom: '#a16207',
    colorTo: '#f5f5f4',
  },
  {
    id: 'polonnaruwa',
    name: 'Polonnaruwa',
    nameSi: 'පොළොන්නරුව',
    nameTa: 'பொலன்னறுவை',
    province: Province.NORTH_CENTRAL,
    tagline: 'Medieval capital by the great sea',
    description: 'The Gal Vihara stone Buddhas and Parakrama Samudra, the king’s own inland sea.',
    famousFor: ['Gal Vihara', 'Parakrama Samudra', 'Ancient city', 'Minneriya elephants'],
    colorFrom: '#78350f',
    colorTo: '#65a30d',
  },
  {
    id: 'badulla',
    name: 'Badulla',
    nameSi: 'බදුල්ල',
    nameTa: 'பதுளை',
    province: Province.UVA,
    tagline: 'Waterfalls, trains and Ella views',
    description: 'The blue train over the Nine Arch Bridge, Ella Rock sunrises and waterfalls around every bend.',
    famousFor: ['Ella', 'Nine Arch Bridge', 'Dunhinda Falls', 'Little Adam’s Peak'],
    colorFrom: '#166534',
    colorTo: '#0ea5e9',
  },
  {
    id: 'monaragala',
    name: 'Monaragala',
    nameSi: 'මොණරාගල',
    nameTa: 'மொனராகலை',
    province: Province.UVA,
    tagline: 'Peacock rock and sacred Kataragama',
    description: 'Sugar cane fields, the pilgrim town of Kataragama and the giant Buduruwagala carvings.',
    famousFor: ['Kataragama', 'Buduruwagala', 'Maligawila Buddha', 'Sugar cane'],
    colorFrom: '#4d7c0f',
    colorTo: '#0d9488',
  },
  {
    id: 'ratnapura',
    name: 'Ratnapura',
    nameSi: 'රත්නපුරය',
    nameTa: 'இரத்தினபுரி',
    province: Province.SABARAGAMUWA,
    tagline: 'The city of gems',
    description: 'Sapphires from the riverbeds, the Sinharaja rainforest and a pilgrim trail up Sri Pada.',
    famousFor: ['Gem mining', 'Sinharaja Forest', 'Sri Pada trail', 'Bopath Ella'],
    colorFrom: '#1e3a8a',
    colorTo: '#9333ea',
  },
  {
    id: 'kegalle',
    name: 'Kegalle',
    nameSi: 'කෑගල්ල',
    nameTa: 'கேகாலை',
    province: Province.SABARAGAMUWA,
    tagline: 'Elephants and white-water rivers',
    description: 'Pinnawala’s elephants, Kitulgala’s rapids and green hills rolling towards the central highlands.',
    famousFor: ['Pinnawala', 'Kitulgala rafting', 'Rubber estates', 'Waterfalls'],
    colorFrom: '#15803d',
    colorTo: '#0f766e',
  },
];
